# config.yml
backend:
  name: git-gateway
  branch: main # BURAYI KONTROL EDİN: Kendi GitHub deponuzun ana dal adı (main veya master)

# Bu kısım kimlik doğrulama için gerekli, değişiklik yapmayın
publish_mode: editorial_workflow # Taslak ve yayınlama iş akışı sağlar

# Medya (görsel) ayarları
media_folder: "comments" # Yüklenen resimlerin kaydedileceği GitHub'daki klasör (root'a göre)
public_folder: "/comments" # Bu klasördeki resimlere web üzerinden erişim yolu (root'a göre)

# Koleksiyonlar (yönetilecek içerik türleri)
collections:
  - name: "comments"
    label: "Müşteri Yorumları"
    folder: "content/comments"
    create: true
    slug: "{{slug}}"
    format: json # BURAYI EKLEYİN
    extension: json # BURAYI EKLEYİN (dosyaların .json uzantısıyla kaydedilmesini sağlar)
    fields:
      - {label: "Başlık (Internal Use)", name: "title", widget: "string", required: true}
      - {label: "Yorum Görseli", name: "image", widget: "image", allow_multiple: false, required: true}
      - {label: "Alternatif Metin (SEO)", name: "altText", widget: "string", required: false}