# config.yml
backend:
  name: git-gateway
  branch: main # BURAYI KONTROL EDİN: Kendi GitHub deponuzun ana dal adı (main veya master)

# Bu kısım kimlik doğrulama için gerekli, değişiklik yapmayın
publish_mode: editorial_workflow # Taslak ve yayınlama iş akışı sağlar

# Medya (görsel) ayarları
media_folder: "comments" # Yüklenen resimlerin kaydedileceği GitHub'daki klasör (root'a göre)
public_folder: "/comments" # Bu klasördeki resimlere web üzerinden erişim yolu (root'a göre)

# Koleksiyonlar (yönetilecek içerik türleri)
collections:
  - name: "comments" # CMS'te görünen koleksiyon adı (örn: URL'de /admin/#/collections/comments)
    label: "Müşteri Yorumları" # Yönetici panelinde görünen başlık
    folder: "content/comments" # Markdown/YAML dosyalarının kaydedileceği klasör (root'a göre)
    create: true # Yeni yorum eklemeye izin ver
    slug: "{{slug}}" # Oluşturulan dosya adları için slug (örn: my-new-comment.md)
    fields: # Her bir yorum öğesi için hangi alanları düzenleyecekler
      - {label: "Başlık (Internal Use)", name: "title", widget: "string", required: true}
      - {label: "Yorum Görseli", name: "image", widget: "image", allow_multiple: false, required: true}
      - {label: "Alternatif Metin (SEO)", name: "altText", widget: "string", required: false}
      # Eğer yorum metni de eklemek isterseniz, aşağıdaki satırı aktif edin:
      # - {label: "Yorum Metni (İsteğe Bağlı)", name: "text", widget: "markdown", required: false}